pathauto.settings:
  type: config_object
  mapping:
    enabled_entity_types:
      label: Enabled entity types
      type: sequence
      sequence:
        type: string
    punctuation:
      type: sequence
      sequence:
        type: integer
    verbose:
      type: boolean
    separator:
      type: string
    max_length:
      type: integer
    max_component_length:
      type: integer
    transliterate:
      type: boolean
    reduce_ascii:
      type: boolean
    case:
      type: boolean
    ignore_words:
      type: string
    update_action:
      type: integer
    safe_tokens:
      label: Tokens that are safe to use and do not need to be cleaned.
      type: sequence
      sequence:
        type: string

action.configuration.pathauto_update_alias:
  type: action_configuration_default
  label: 'Update URL alias'
