block.settings.entity_field:*:*:
  type: block_settings
  label: 'Entity field block'
  mapping:
    formatter:
      type: mapping
      label: 'Field formatter'
      mapping:
        type:
          type: string
          label: 'Format type machine name'
        weight:
          type: integer
          label: 'Weight'
        region:
          type: string
          label: 'Region'
        label:
          type: string
          label: 'Label setting machine name'
        settings:
          type: field.formatter.settings.[%parent.type]
          label: 'Settings'
        third_party_settings:
          type: sequence
          label: 'Third party settings'
          sequence:
            type: field.formatter.third_party.[%key]
