# Schema for the configuration files of the Contact module.

contact.form.*:
  type: config_entity
  label: 'Contact form'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    recipients:
      type: sequence
      label: 'Recipients'
      sequence:
        type: email
        label: 'Email address'
    reply:
      type: text
      label: 'Auto-reply'
    weight:
      type: integer
      label: 'Weight'

contact.settings:
  type: config_object
  label: 'Contact settings'
  mapping:
    default_form:
      type: string
      label: 'Default form identifier'
    flood:
      type: mapping
      label: 'Flood control'
      mapping:
        limit:
          type: integer
          label: 'Limit'
        interval:
          type: integer
          label: 'Interval'
    user_default_enabled:
      type: boolean
      label: 'Personal contact form enabled by default'

migrate.source.d6_contact_settings:
  type: migrate_source_sql
  label: 'Drupal 6 contact settings'
  mapping:
    variables:
      type: sequence
      label: 'Variables'
      sequence:
        type: string
        label: 'Variable'
