id: d6_text_settings
label: Drupal 6 teaser length configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - teaser_length
process:
  default_summary_length: teaser_length
destination:
  plugin: config
  config_name: text.settings
