id: d6_file_settings
label: Drupal 6 file configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - file_description_type
    - file_description_length
    - file_icon_directory
process:
  'description/type': file_description_type
  'description/length': file_description_length
  'icon/directory': file_icon_directory
destination:
  plugin: config
  config_name: file.settings
