<?php

/**
 * @file
 * Contains metatag_open_graph_products.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function metatag_open_graph_products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the metatag_open_graph_products module.
    case 'help.page.metatag_open_graph_products':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides additional Open Graph Protocol meta tags for describing products.') . '</p>';
      return $output;

    default:
  }
}
