migrate.source.d6_view_mode:
  type: migrate_source_sql
  label: 'Drupal 6 view mode'
  mapping:
    constants:
      type: mapping
      label: 'Constants'
      mapping:
        targetEntityType:
          type: string
          label: 'Target entity type'
        status:
          type: boolean
          label: 'Status'

migrate.source.d6_node_type:
  type: migrate_source_sql
  label: 'Drupal 6 node type'
  mapping:
    constants:
      type: migrate_entity_constant
      label: 'Constants'

migrate.source.d6_node:
  type: migrate_source_sql
  label: 'Drupal 6 node'
  mapping:
    node_type:
      # The node type can be specified both as a string ID of a node type or an
      # array of node type IDs, so there is no way to consistently parse this.
      type: ignore
      label: 'Node type'

migrate.source.d6_node_revision:
  type: migrate_source_sql
  label: 'Drupal 6 node'
  mapping:
    node_type:
      # The node type can be specified both as a string ID of a node type or an
      # array of node type IDs, so there is no way to consistently parse this.
      type: ignore
      label: 'Node type'
