services:
  access_check.settings_tray.block.settings_tray_form:
    class: Drupal\settings_tray\Access\BlockPluginHasSettingsTrayFormAccessCheck
    tags:
      - { name: access_check, applies_to: _access_block_plugin_has_settings_tray_form }
