drupal.settings_tray:
  version: VERSION
  js:
    js/settings_tray.js: {}
  css:
    component:
      css/settings_tray.module.css: {}
      css/settings_tray.motion.css: {}
      css/settings_tray.toolbar.css: {}
    theme:
      # @todo Set the group higher than CSS_AGGREGATE_THEME so that it overrides
      #   both jQuery UI and Classy's dialog.css, remove in
      #   https://www.drupal.org/node/1945262.
      css/settings_tray.theme.css: { group: 200 }
  dependencies:
    - core/jquery
    - core/drupal
    - core/jquery.once
    - core/drupal.ajax
drupal.off_canvas:
  version: VERSION
  js:
    js/off-canvas.js: {}
  css:
    base:
      css/off-canvas.reset.css: {}
      css/off-canvas.base.css: {}
      css/off-canvas.css: {}
      css/off-canvas.theme.css: { group: 200 }
    component:
      css/off-canvas.motion.css: {}
      css/off-canvas.button.css: {}
      css/off-canvas.form.css: {}
      css/off-canvas.table.css: {}
      css/off-canvas.details.css: {}
      css/off-canvas.tabledrag.css: {}
      css/off-canvas.dropbutton.css: {}

  dependencies:
    - core/jquery
    - core/drupal
    - core/drupal.ajax
    - core/drupal.announce
    - core/drupal.dialog
    - core/drupal.dialog.ajax
