id: d6_node_settings
label: Drupal 6 node configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - node_admin_theme
process:
  use_admin_theme: node_admin_theme
destination:
  plugin: config
  config_name: node.settings
