name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2020-03-30
version: '9.0.0-beta2'
project: 'drupal'
datestamp: 1585597457
