id: d6_syslog_settings
label: Drupal 6 system log configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - syslog_identity
    - syslog_facility
process:
  identity: syslog_identity
  facility: syslog_facility
destination:
  plugin: config
  config_name: syslog.settings
