id: d7_language_content_menu_settings
label: Drupal 7 language content menu settings
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: d7_language_content_settings_menu
  constants:
    target_type: 'menu_link_content'
    langcode: 'site_default'
process:
  target_bundle:
    -
      plugin: migration_lookup
      migration: d7_menu
      source: menu_name
    -
      plugin: skip_on_empty
      method: row
  # State is the value in the i18n_mode column of menu_custom table
  # 0: No multilingual options.
  # 1: Localize. Localizable object. Run through the localization system
  # 2: Fixed Language. Predefined language for this object and all related ones
  # 4: Translate. Multilingual objects, translatable but not localizable.
  # 5: Objects are translatable (if they have language or localizable if not)
  language_alterable:
    plugin: static_map
    source: i18n_mode
    map:
      0: false
      1: true
      2: false
      4: true
      5: true
  'third_party_settings/content_translation/enabled':
    plugin: static_map
    source: i18n_mode
    map:
      0: false
      1: true
      2: false
      4: false
      5: true
  target_entity_type_id: 'constants/target_type'
  default_langcode:
    plugin: default_value
    default_value: site_default
    source: language
destination:
  plugin: entity:language_content_settings
migration_dependencies:
  required:
    - d7_menu
