core.entity_view_display.*.*.*.third_party.layout_builder:
  type: mapping
  label: 'Per-view-mode Layout Builder settings'
  mapping:
    allow_custom:
      type: boolean
      label: 'Allow a customized layout'
    sections:
      type: sequence
      sequence:
        type: layout_builder.section

layout_builder.section:
  type: mapping
  label: 'Layout section'
  mapping:
    layout_id:
      type: string
      label: 'Layout ID'
    layout_settings:
      type: layout_plugin.settings.[%parent.layout_id]
      label: 'Layout settings'
    components:
      type: sequence
      label: 'Components'
      sequence:
        type: layout_builder.component

layout_builder.component:
  type: mapping
  label: 'Component'
  mapping:
    configuration:
      type: block.settings.[id]
    region:
      type: string
      label: 'Region'
    uuid:
      type: uuid
      label: 'UUID'
    weight:
      type: integer
      label: 'Weight'
    additional:
      type: ignore
      label: 'Additional data'
